export const Users = [
    {
      id:1,
      profilePicture: "https://images4.alphacoders.com/653/thumbbig-653541.webp",
      username: "Petra Rall",
    },
    {
      id:2,
      profilePicture: "https://static.wikia.nocookie.net/shingekinokyojin/images/8/8f/Isabel_Magnolia_%28Anime%29_character_image.png/revision/latest/scale-to-width-down/150?cb=20170629015437",
      username: "Isabel Magnolia",
    },
    {
      id:3,
      profilePicture: "https://static.wikia.nocookie.net/shingekinokyojin/images/e/e4/Hange_Zo%C3%AB_%28Anime%29_character_image.png/revision/latest/scale-to-width-down/150?cb=20210221212604",
      username: "Hange Zoe",
    },
    {
      id:4,
      profilePicture: "https://static.wikia.nocookie.net/shingekinokyojin/images/0/0a/Sasha_Braus_%28Anime%29_character_image.png/revision/latest/scale-to-width-down/150?cb=20210124211650",
      username: "Sasha Braus",
    },
    {
      id:5,
      profilePicture: "https://static.wikia.nocookie.net/shingekinokyojin/images/1/12/Lynne_%28Anime%29_character_image.png/revision/latest/scale-to-width-down/150?cb=20180217185349",
      username: "Lynne",
    },
    {
      id:6,
      profilePicture: "https://images.alphacoders.com/100/thumbbig-1000461.webp",
      username: "Mikasa Ackerman",
    },
    {
      id:7,
      profilePicture: "https://static.wikia.nocookie.net/shingekinokyojin/images/f/f7/Rico_Brzenska_%28Anime%29_character_image.png/revision/latest/scale-to-width-down/150?cb=20170430033417",
      username: "Rico Brzenska",
    },
    {
      id:8,
      profilePicture: "https://static.wikia.nocookie.net/shingekinokyojin/images/9/9a/Mina_Carolina_%28Anime%29_character_image.png/revision/latest/scale-to-width-down/150?cb=20130820182300",
      username: "Mina Carolina",
    },
    {
      id:9,
      profilePicture: "https://static.wikia.nocookie.net/shingekinokyojin/images/6/66/Annie_Leonhart_%28Anime%29_character_image.png/revision/latest/scale-to-width-down/150?cb=20171207050656",
      username: "Annie Leonhart",
    },
    {
      id:10,
      profilePicture: "https://static.wikia.nocookie.net/shingekinokyojin/images/0/05/Frieda_Reiss_%28Anime%29_character_image.png/revision/latest/scale-to-width-down/150?cb=20180907103107",
      username: "Frieda Reiss",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Love For All, Hatred For None.",
      photo: "https://images8.alphacoders.com/505/thumbbig-505616.webp",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "https://images4.alphacoders.com/607/thumbbig-607877.webp",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Every moment is a fresh beginning.",
      photo: "https://images3.alphacoders.com/653/thumbbig-653529.webp",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "https://images2.alphacoders.com/665/thumbbig-665356.webp",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "https://images7.alphacoders.com/567/thumbbig-567918.webp",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "https://images8.alphacoders.com/403/thumbbig-403477.webp",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Never regret anything that made you smile.",
      photo: "assets/post/7.jpeg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "https://images8.alphacoders.com/473/thumbbig-473221.webp",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Change the world by being yourself.",
      photo: "https://images5.alphacoders.com/607/thumbbig-607878.webp",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      photo: "https://images5.alphacoders.com/607/thumbbig-607699.webp",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];