export const Users = [
    {
      id:1,
      profilePicture: "person/1.jpeg",
      username: "petra",
    },
    {
      id:2,
      profilePicture: "person/2.jpeg",
      username: "Isabel Magnolia",
    },
    {
      id:3,
      profilePicture: "person/3.jpeg",
      username: "Hange Zoe",
    },
    {
      id:4,
      profilePicture: "person/4.jpeg",
      username: "Sasha Braus",
    },
    {
      id:5,
      profilePicture: "person/5.jpeg",
      username: "Lynne",
    },
    {
      id:6,
      profilePicture: "person/6.jpeg",
      username: "Mikasa Ackerman",
    },
    // {
    //   id:7,
    //   profilePicture: "https://static.wikia.nocookie.net/shingekinokyojin/images/f/f7/Rico_Brzenska_%28Anime%29_character_image.png",
    //   username: "Rico Brzenska",
    // },
    // {
    //   id:8,
    //   profilePicture: "https://static.wikia.nocookie.net/shingekinokyojin/images/9/9a/Mina_Carolina_%28Anime%29_character_image.png",
    //   username: "Mina Carolina",
    // },
    // {
    //   id:9,
    //   profilePicture: "https://static.wikia.nocookie.net/shingekinokyojin/images/6/66/Annie_Leonhart_%28Anime%29_character_image.png",
    //   username: "Annie Leonhart",
    // },
    // {
    //   id:10,
    //   profilePicture: "https://static.wikia.nocookie.net/shingekinokyojin/images/0/05/Frieda_Reiss_%28Anime%29_character_image.png",
    //   username: "Frieda Reiss",
    // },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Love For All, Hatred For None.",
      photo: "https://images8.alphacoders.com/505/thumbbig-505616.webp",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "https://images4.alphacoders.com/607/thumbbig-607877.webp",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Every moment is a fresh beginning.",
      photo: "assests/person/1.jpeg",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "person/1.jpeg",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "https://images7.alphacoders.com/567/thumbbig-567918.webp",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "person/1.jpeg",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    // {
    //   id: 7,
    //   desc: "Never regret anything that made you smile.",
    //   photo: "post/7.jpeg",
    //   date: "2 days ago",
    //   userId: 7,
    //   like: 52,
    //   comment: 3,
    // },
    // {
    //   id: 8,
    //   photo: "https://images8.alphacoders.com/473/thumbbig-473221.webp",
    //   date: "3 days ago",
    //   userId: 8,
    //   like: 15,
    //   comment: 1,
    // },
    // {
    //   id: 9,
    //   desc: "Change the world by being yourself.",
    //   photo: "https://images5.alphacoders.com/607/thumbbig-607878.webp",
    //   date: "5 days ago",
    //   userId: 9,
    //   like: 11,
    //   comment: 2,
    // },
    // {
    //   id: 10,
    //   photo: "https://images5.alphacoders.com/607/thumbbig-607699.webp",
    //   date: "1 week ago",
    //   userId: 10,
    //   like: 104,
    //   comment: 12,
    // },
  ];